# Generated by Django 3.2.7 on 2023-05-12 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=2000, null=True, verbose_name='Холбоос')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр')),
                ('quantity', models.IntegerField(null=True, verbose_name='Тоо ширхэг')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Өнгө')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Тайлбар')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='Тайлбар')),
                ('is_from_application', models.BooleanField(blank=True, default=False, verbose_name='Is from application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалга',
                'db_table': 'order',
            },
        ),
    ]
