# Generated by Django 3.2.7 on 2023-05-13 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20230512_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Хэрэглэгчид илгээх тайлбар'),
        ),
        migrations.AddField(
            model_name='order',
            name='calculate_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order2', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Үнэ'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Устгасан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Хүргэлтийн үнэ'),
        ),
        migrations.AddField(
            model_name='order',
            name='hansh',
            field=models.FloatField(blank=True, null=True, verbose_name='Ханш'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Үйлчилгээний хураамж'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Хятад доторх тээврийн зардал'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Шинэ'), ('F', 'Цуцалсан'), ('D', 'Дууссан'), ('B', 'Буцаагдсан'), ('O', 'Захиалсан'), ('C', 'Үнэ бодогдсон'), ('P', 'Төлбөр төлөгдсөн'), ('Q', 'Мэдээлэл буруу')], default='N', max_length=1),
        ),
    ]
