# Generated by Django 3.2.7 on 2023-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_order_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Нэр')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Утас')),
                ('message', models.TextField(blank=True, default='', null=True, verbose_name='Санал хүсэлт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Илгээсэн огноо')),
            ],
            options={
                'verbose_name': 'Санал хүсэлт',
                'verbose_name_plural': 'Санал хүсэлт',
                'db_table': 'message_request',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='calculate_user',
        ),
    ]
