# Generated by Django 3.2.7 on 2023-05-24 18:48

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20230525_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=2500, upload_to=profiles.models.PathAndRename('picture/'), verbose_name='Зураг')),
                ('promo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Промо текст')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Гарчиг')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Илгээсэн огноо')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Устгасан')),
            ],
            options={
                'verbose_name': 'Мэдээ мэдээлэл',
                'verbose_name_plural': 'Мэдээ мэдээлэл',
                'db_table': 'news',
            },
        ),
    ]
