# Generated by Django 3.2.7 on 2023-05-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sequence',
            field=models.IntegerField(null=True, verbose_name='Дараалал'),
        ),
    ]
