# Generated by Django 3.2.7 on 2023-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_news_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Утас')),
                ('email', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имэйл')),
                ('address', models.TextField(blank=True, default='', null=True, verbose_name='Хаяг')),
                ('small_description', models.TextField(blank=True, default='', null=True, verbose_name='Богино мэдээлэл')),
                ('fb', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фэйсбүүк линк')),
                ('insta', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Инста линк')),
            ],
            options={
                'verbose_name': 'Үндсэн мэдээлэл',
                'verbose_name_plural': 'Үндсэн мэдээлэл',
                'db_table': 'base_info',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='promo',
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Холбоос'),
        ),
    ]
