# Generated by Django 3.2.7 on 2023-06-07 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_help_helpcontent_helpstep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpstep',
            options={'verbose_name': 'Тусламж алхам', 'verbose_name_plural': 'Тусламж алхам'},
        ),
        migrations.RemoveField(
            model_name='helpstep',
            name='contents',
        ),
        migrations.AddField(
            model_name='helpstep',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.DeleteModel(
            name='HelpContent',
        ),
    ]
