# Generated by Django 3.2.7 on 2023-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_helpstep_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='sequence',
            field=models.IntegerField(null=True, verbose_name='Дараалал'),
        ),
        migrations.AddField(
            model_name='helpstep',
            name='sequence',
            field=models.IntegerField(null=True, verbose_name='Дараалал'),
        ),
    ]
