# Generated by Django 3.2.7 on 2023-06-07 12:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20230607_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Гарчиг')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('sequence', models.IntegerField(null=True, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Бидний тухай',
                'verbose_name_plural': 'Бидний тухай',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='UseOfTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Гарчиг')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Контент')),
                ('sequence', models.IntegerField(null=True, verbose_name='Дараалал')),
            ],
            options={
                'verbose_name': 'Үйлчилгээний нөхцөл',
                'verbose_name_plural': 'Үйлчилгээний нөхцөл',
                'db_table': 'use_of_terms',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Холбоос'),
        ),
    ]
