# Generated by Django 3.2.7 on 2023-06-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20230611_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hansh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hansh', models.FloatField(blank=True, null=True, verbose_name='Ханш')),
            ],
            options={
                'verbose_name': 'Ханш',
                'verbose_name_plural': 'Ханш',
                'db_table': 'hansh',
            },
        ),
    ]
