# Generated by Django 3.2.7 on 2023-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='position',
            field=models.CharField(choices=[('L', 'Зүүн'), ('R', 'Баруун'), ('C', 'Төв')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Захиалгын дугаар'),
        ),
        migrations.AddField(
            model_name='order',
            name='ub_shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Эрээнээс-Улаанбаатар үнэ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Хятад доторх тээврийн үнэ'),
        ),
    ]
