# Generated by Django 3.2.7 on 2023-06-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20230619_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='position',
            field=models.CharField(choices=[('L', 'Зүүн'), ('R', 'Баруун'), ('C', 'Төв')], default='C', max_length=1, verbose_name='Текстийн байрлал'),
        ),
    ]
