# Generated by Django 3.2.7 on 2023-10-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_news_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=200, null=True, verbose_name='Тоо ширхэг'),
        ),
    ]
